### PR TITLE
Initial setup of repo with `ddev platformsh` etc, fixes #4, fixes #5, fixes #6, fixes #12

### LINKED ISSUE #4: Add `ddev platform` command
Shortcut for `ddev exec platform`

### LINKED ISSUE #5: Update `platform` CLI upon startup
Either on `post-start` or when running `ddev get`

`ddev exec platform self:update --no-major --yes`

### LINKED ISSUE #6: Set `/app` as working dir
In Platform.sh container, the "app dir" is `/app`. As such, one expect the same in a local container.
`/app` might be a symlink to `/var/www/html`.

The doc root (or web root) is always relative to this app dir and is [defined in `.platform.app.yaml`](https://docs.platform.sh/create-apps.html#a-minimal-application) ([more details from the YAML reference](https://docs.platform.sh/create-apps/app-reference.html#locations))

### LINKED ISSUE #12: Database type change or version downgrade can be painful
As with any database server, changing the server while keeping the same data may often not work out. For example, if you have a working database on MariaDB 10.3, and you change the server type to MySQL 8.0, it will choke on the way up. And DDEV currently has no easy way to know the type of the existing data, in /var/lib/mysql even though the type is in there in a file that DDEV adds, but it can't be seen without starting a container with that volume mounted.

People stumble on this regularly and the docs cover it, and it makes sense.

But it would be a much better user experience if we could:

* Detect the version of the database in the volume mount.
* Detect if there is actually data there
* If a downgrade or a type change, warn people or... if the 'db' database is actually empty, rebuild the whole thing silently.

Discussion in https://platformsh.slack.com/archives/C03GRG19L2E/p1654616860043129

This issue should probably be moved to drud/ddev, but dropping it here because it has significant impact on this project, where most people will probably have an existing mariadb:10.3 database (but possibly empty) before pulling this add-on, making it hard to give them the type they have in the upstream hosting (if it's different).

### PR DESCRIPTION
**Pull request by rfay**
Related issues:
- [x] #4 (fixes #4)
- [ ] #5 
- [x] #6
- [x] #12 

To try this out, you can `ddev get https://github.com/rfay/ddev-platformsh/tarball/20220601_initial_experiments`

### CODE REVIEW

**Comment by rfay** [comment]
@lolautruche I haven't figured out where to get environment variables from. I see the list you provided in https://docs.platform.sh/development/variables/use-variables.html#use-platformsh-provided-variables but the only way I've been able to access those is `platform ssh` and `env | grep PLATFORM_` - I thought they would be available via a platform command but I haven't found one.

**Comment by rfay** [comment]
Thanks @lolautruche - The question is how to *get* the PLATFORM_ variables... do you have to `platform ssh`? That seems hard, I'd expect one of the platform commands to provide them.

**Comment by lolautruche** [comment]
We don't have to get them, we need to create them consistently in the local containers, according to the DDEV environment. In other words, we *emulate* their presence, with local values.

**Comment by rfay** [comment]
So get them from a secondary sources... that seems awkward. And don't we need to use those values? What's the recommended secondary source? The .platform.app or whatever?

**Comment by lolautruche** [comment]
`$PLATFORM_` env vars describe the current environment. In our case, the environment will be a DDEV container. Some variables are sourced from `.platform.app.yaml` (e.g., `$PLATFORM_APPLICATION_NAME`, or `$PLATFORM_APPLICATION` which is a base64 JSON blob), but others depend on the environment (e.g. `$PLATFORM_BRANCH` which is the actual git branch, or `$PLATFORM_DOCUMENT_ROOT` which gives the absolute path for the document root.

Here are a few examples that I would expect to get from the DDEV container:
| Var name                  | Value                                                                  |
|---------------------------|------------------------------------------------------------------------|
| `$PLATFORM_BRANCH`        | The current Git branch                                                 |
| `$PLATFORM_DOCUMENT_ROOT` | `/var/www/html/web` or `/app/web` (depends on the configured web root) |
| `$PLATFORM_PROJECT`       | Current Platform.sh project ID                                         |
| `$PLATFORM_SMTP_HOST`     | Mailhog SMTP host                                                      |

Regarding `$PLATFORM_RELATIONSHIPS`, it is a JSON blob base64 encoded which describes how to access to a related service (e.g., the database).
Example:

```
$ echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq
{
  "database": [
    {
      "username": "user",
      "scheme": "mysql",
      "service": "db",
      "fragment": null,
      "ip": "169.254.255.8",
      "hostname": "4rrtb6sgmu5heslnidt5lfpvmi.db.service._.eu-3.platformsh.site",
      "public": false,
      "cluster": "6j4ypl5iendqc-workshop-5ziq2gq",
      "host": "database.internal",
      "rel": "mysql",
      "query": {
        "is_master": true
      },
      "path": "main",
      "password": "",
      "type": "mariadb:10.4",
      "port": 3306,
      "host_mapped": false
    }
  ]
}
```

`hostname`, `port`, `path` (DB name), `username`, `password`, etc... should get the corresponding for the DDEV database, e.g.:

```json
{
  "database": [
    {
      "username": "db",
      "scheme": "mysql",
      "service": "db",
      "fragment": null,
      "ip": "172.20.0.4",
      "hostname": "ddev-myapp-db",
      "public": false,
      "cluster": "",
      "host": "ddev-myapp-db",
      "rel": "mysql",
      "query": {
        "is_master": true
      },
      "path": "db",
      "password": "db",
      "type": "mariadb:10.4",
      "port": 3306,
      "host_mapped": false
    }
  ]
}
```

**Comment by rfay** [comment]
I'm going to go ahead and pull this one, and people can start to give it a little bit of attention, then we can prioritize next steps.

**Pull request merged**
