### PR TITLE
Allow arbitrary database type derived from .platform.app, fixes #13

### LINKED ISSUE #13: Go template processing failing at install
Using the latest HEAD version of DDEV, running `ddev get platformsh/ddev-platformsh` fails:

## Error Details
`template: processAction:10:84: executing "processAction" at <.services.dbmysql.type>: invalid value; expected string`
<details>
  <summary>Click to see the full error</summary>

```
could not process pre-install action '#ddev-nodisplay
#todo: This simplistic approach doesn't work for postgres; volume name is different
#and the database type file is different too
if docker volume ls | grep ${DDEV_PROJECT}-mariadb; then
  export current_db_version="$(docker run --rm -w /db -v ${DDEV_PROJECT}-mariadb:/db busybox cat db_mariadb_version.txt)"
  if [ -z "${current_db_version}" ]; then
    echo "something went wrong, current_db_version is empty" && false
  fi
  export upstream_db="{{ regexReplaceAll "oracle-" (regexReplaceAll ":.*$" .services.dbmysql.type "") "" }}:{{ regexReplaceAll "^.*:" .services.dbmysql.type "" }}"
  echo "Current db is ${current_db_version/_/:} (${current_db_version})"
  echo "New db is ${upstream_db}"
  if [ "${current_db_version/_/:}" != "${upstream_db}" ]; then
    printf "There is an existing database in this project that doesn\'t match the upstream database type.\nPlease back up this database and then \"ddev delete\" so the new database can be created.\n"
    false
  else
    echo "database versions match: ${current_db_version/_/:}=${upstream_db}"
  fi
fi
': could not parse/execute action 'set -eu -o pipefail
#ddev-nodisplay
#todo: This simplistic approach doesn't work for postgres; volume name is different
#and the database type file is different too
if docker volume ls | grep ${DDEV_PROJECT}-mariadb; then
  export current_db_version="$(docker run --rm -w /db -v ${DDEV_PROJECT}-mariadb:/db busybox cat db_mariadb_version.txt)"
  if [ -z "${current_db_version}" ]; then
    echo "something went wrong, current_db_version is empty" && false
  fi
  export upstream_db="{{ regexReplaceAll "oracle-" (regexReplaceAll ":.*$" .services.dbmysql.type "") "" }}:{{ regexReplaceAll "^.*:" .services.dbmysql.type "" }}"
  echo "Current db is ${current_db_version/_/:} (${current_db_version})"
  echo "New db is ${upstream_db}"
  if [ "${current_db_version/_/:}" != "${upstream_db}" ]; then
    printf "There is an existing database in this project that doesn\'t match the upstream database type.\nPlease back up this database and then \"ddev delete\" so the new database can be created.\n"
    false
  else
    echo "database versions match: ${current_db_version/_/:}=${upstream_db}"
  fi
fi
': template: processAction:10:84: executing "processAction" at <.services.dbmysql.type>: invalid value; expected string
```
</details>

## DDEV version info
```json
{
  "level": "info",
  "raw": {
    "DDEV version": "vHEAD-ef00de8",
    "architecture": "arm64",
    "build info": "BUILDINFO should have new info",
    "db": "drud/ddev-dbserver-mariadb-10.3:v1.19.3",
    "dba": "phpmyadmin:5",
    "ddev-ssh-agent": "drud/ddev-ssh-agent:v1.19.0",
    "docker": "20.10.14",
    "docker-compose": "v2.5.1",
    "docker-platform": "docker-desktop",
    "mutagen": "0.14.0",
    "os": "darwin",
    "router": "drud/ddev-router:v1.19.3",
    "web": "drud/ddev-webserver:20220619_add_phpstorm_coverage_directory"
  },
  "time": "2022-06-23T10:35:05+02:00"
}
```

## Platform files
[platform_files.zip](https://github.com/platformsh/ddev-platformsh/files/8967621/platform_files.zip)

### PR DESCRIPTION
**Pull request by rfay**
* #13 

It turns out that services.yml/.platform.app can use any random value for the db section; it has to be derived from the arbitrary value used in .platform.app. See #13

### CODE REVIEW

**Comment by rfay** [comment]
Tested on mariadb, mysql, and postgres with the Drupal template, but nothing else. Could you please give this a try @lolautruche, `ddev get https://github.com/platformsh/ddev-platformsh/tarball/20220623_arbitrary_db_header` - you'll want to do a `ddev platform pull` for full testing as well.

**Comment by lolautruche** [comment]
```
$ ddev restart
Failed to get project(s): /Users/lolautruche/workspace/blackfire/bigfoot-symfony/.ddev/config.yaml exists but cannot be read. It may be invalid due to a syntax error.: unable to load config file /Users/lolautruche/workspace/blackfire/bigfoot-symfony/.ddev/config.platformsh.yaml: invalid configuration in /Users/lolautruche/workspace/blackfire/bigfoot-symfony/.ddev/config.yaml: yaml: line 15: mapping values are not allowed in this context
```

### Generated `config.platformsh.yaml`:
```yaml
# #ddev-generated
# Generated configuration based on platform.sh project configuration
 


php_version: 8.1
database:
  type: mariadb
  version: 10.4

docroot: public



  - exec: set -x -e&&&&symfony-deploy


```

**Comment by lolautruche** [comment]
@rfay it's the same than for #13

**Comment by rfay** [comment]
Ah, this is not a composer build, and the `hooks` statement was embedded in composer.

```
      {{ if eq .platformapp.build.flavor "composer" }}
      hooks:
        post-start:
        - composer: install
      {{ end }}
```

**Comment by lolautruche** [comment]
Mmm still having the same issue. Maybe a cache problem downloading the tarball?

**Comment by lolautruche** [comment]
```yaml
# #ddev-generated
# Generated configuration based on platform.sh project configuration
 


php_version: 8.1
database:
  type: mariadb
  version: 10.4

docroot: public



  - exec: set -x -e&&&&symfony-deploy


```

**Comment by rfay** [comment]
Silly me. I committed but failed to push. Sorry. I've been trying to use the IDE for git operations after doing everything git on the command line for more than a decade, and it doesn't come easily.

**Comment by lolautruche** [comment]
It works 🎉 !

The post-start script does indeed fail on `symfony-deploy`, which was expected. This is because the [build hook script](https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook) in my `.platform.app.yaml` was not executed in the first place:

```yaml
hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | bash
        symfony-build
    deploy: |
        set -x -e

        symfony-deploy
```

**Pull request merged**
