### PR TITLE
Attempt to get project ID from local config

### PR DESCRIPTION
**Pull request by bserem**
Solves #28

### CODE REVIEW

**Comment by rfay** [comment]
The idiomatic way to do this will be to add .platform/local/project.yaml to `yaml_read_files` like
```
yaml_read_files:
  platformapp: .platform.app.yaml
  services: .platform/services.yaml
  localproject: .platform/local/project.yaml
```
and then use 
```
  {{ if .localproject.id }}
```

**Comment by rfay** [comment]
Just a reminder though, since local/project.yaml is innately gitignored, this won't often work unless the platform tool has already been used locally.

```
$ git add local/project.yaml
The following paths are ignored by one of your .gitignore files:
.platform/local
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```

**Comment by rfay** [comment]
@bserem Would you mind removing the `ddev-get` label on your fork, https://github.com/bserem/ddev-platformsh ? It causes it to show up in `ddev get --list --all`. Thanks!

**Comment by bserem** [comment]
Current workload is high, especially after Drupalcon, so I'm making a fork of this that automatically populates the ID.

It is not ready to be merged, since it will not work if `.platform/local/project.yaml` does not exist in the local repo.

**Comment by rfay** [comment]
I'm going to close this for now, but happy to pick it up again, just say the word. Judging from the docs, I don't think it can be done predictably, but am happy to be corrected.

**Pull request closed without merging**
